CREATE TABLE SECURITY_RULES(
  USERNAME VARCHAR(100),
  TERRITORY VARCHAR(20)
);

GRANT SELECT ON TABLE PUBLIC.SECURITY_RULES TO PENTAHO_USER;
GRANT SELECT ON TABLE PUBLIC.SECURITY_RULES TO PENTAHO_ADMIN;

GRANT SELECT ON TABLE PUBLIC.SECURITY_RULES TO "pentaho_user";
GRANT SELECT ON TABLE PUBLIC.SECURITY_RULES TO "pentaho_admin";
