SELECT
F.*
FROM        ORDERFACT F
INNER JOIN  CUSTOMER_W_TER C ON C.CUSTOMERNUMBER = F.CUSTOMERNUMBER
LEFT OUTER JOIN  SECURITY_RULES R ON R.TERRITORY = C.TERRITORY
WHERE lower('admin') = case when 'A' = 'N' THEN lower('admin') ELSE lower(R.USERNAME) END
